
name: 'open_data_platform'
version: '1.0.0'

profile: 'open_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  open_data_platform:
    staging:
      +schema: staging
      +materialized: table
