with cte_source as (
    select * from {{ source('crm', 'airbyte_raw_ticket') }}
)
, parsed as ( 
    select 
    "_airbyte_emitted_at" as inserted_at
    ,_airbyte_data as data
    from cte_source
)
select 
    inserted_at,
    json_query(data, 'strict $.id' WITHOUT ARRAY WRAPPER OMIT QUOTES ) as id,
    json_query(data, 'strict $.campaign_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as campaign_id,
    json_query(data, 'strict $.name' WITHOUT ARRAY WRAPPER OMIT QUOTES) as name,
    json_query(data, 'strict $.name_ascii' WITHOUT ARRAY WRAPPER OMIT QUOTES) as name_ascii,
    json_query(data, 'strict $.customer_type' WITHOUT ARRAY WRAPPER OMIT QUOTES) as customer_type,
    json_query(data, 'strict $.mobile_phone' WITHOUT ARRAY WRAPPER OMIT QUOTES) as mobile_phone,
    json_query(data, 'strict $.home_phone' WITHOUT ARRAY WRAPPER OMIT QUOTES) as home_phone,
    json_query(data, 'strict $.office_phone' WITHOUT ARRAY WRAPPER OMIT QUOTES) as office_phone,
    json_query(data, 'strict $.other_phone' WITHOUT ARRAY WRAPPER OMIT QUOTES ) as other_phone,
    json_query(data, 'strict $.address_interdist' WITHOUT ARRAY WRAPPER OMIT QUOTES) as address_interdist,
    json_query(data, 'strict $.address_interdist1' WITHOUT ARRAY WRAPPER OMIT QUOTES) as address_interdist1,
    json_query(data, 'strict $.address_interdist2' WITHOUT ARRAY WRAPPER OMIT QUOTES) as address_interdist2,
    json_query(data, 'strict $.address_street' WITHOUT ARRAY WRAPPER OMIT QUOTES) as address_street,
    json_query(data, 'strict $.address_ward' WITHOUT ARRAY WRAPPER OMIT QUOTES) as address_ward,
    json_query(data, 'strict $.address_district' WITHOUT ARRAY WRAPPER OMIT QUOTES) as address_district,
    json_query(data, 'strict $.address_district1' WITHOUT ARRAY WRAPPER OMIT QUOTES) as address_district1,
    json_query(data, 'strict $.address_district2' WITHOUT ARRAY WRAPPER OMIT QUOTES) as address_district2,
    json_query(data, 'strict $.province_name' WITHOUT ARRAY WRAPPER OMIT QUOTES) as province_name,
    json_query(data, 'strict $.province_name1' WITHOUT ARRAY WRAPPER OMIT QUOTES) as province_name1,
    json_query(data, 'strict $.province_name2' WITHOUT ARRAY WRAPPER OMIT QUOTES) as province_name2,
    json_query(data, 'strict $.email' WITHOUT ARRAY WRAPPER OMIT QUOTES) as email,
    json_query(data, 'strict $.contract_number' WITHOUT ARRAY WRAPPER OMIT QUOTES) as contract_number,
    json_query(data, 'strict $.date_of_sign' WITHOUT ARRAY WRAPPER OMIT QUOTES) as date_of_sign,
    json_query(data, 'strict $.id_card_no' WITHOUT ARRAY WRAPPER OMIT QUOTES) as id_card_no,
    json_query(data, 'strict $.principal' WITHOUT ARRAY WRAPPER OMIT QUOTES) as principal,
    json_query(data, 'strict $.tenor' WITHOUT ARRAY WRAPPER OMIT QUOTES) as tenor,
    json_query(data, 'strict $.dept' WITHOUT ARRAY WRAPPER OMIT QUOTES) as dept,
    json_query(data, 'strict $.sum_of_payment' WITHOUT ARRAY WRAPPER OMIT QUOTES) as sum_of_payment,
    json_query(data, 'strict $.count_of_payment' WITHOUT ARRAY WRAPPER OMIT QUOTES) as count_of_payment,
    json_query(data, 'strict $.sum_of_panelty' WITHOUT ARRAY WRAPPER OMIT QUOTES) as sum_of_panelty,
    json_query(data, 'strict $.sum_of_panelty_paid' WITHOUT ARRAY WRAPPER OMIT QUOTES) as sum_of_panelty_paid,
    json_query(data, 'strict $.the_rest_of_penalty' WITHOUT ARRAY WRAPPER OMIT QUOTES) as the_rest_of_penalty,
    json_query(data, 'strict $.last_installment' WITHOUT ARRAY WRAPPER OMIT QUOTES) as last_installment,
    json_query(data, 'strict $.dpd' WITHOUT ARRAY WRAPPER OMIT QUOTES) as dpd,
    json_query(data, 'strict $.total_paid' WITHOUT ARRAY WRAPPER OMIT QUOTES) as total_paid,
    json_query(data, 'strict $.productcode' WITHOUT ARRAY WRAPPER OMIT QUOTES) as productcode,
    json_query(data, 'strict $.agent_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as agent_id,
    json_query(data, 'strict $.predictive_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as predictive_id,
    json_query(data, 'strict $.survey_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as survey_id,
    json_query(data, 'strict $.title' WITHOUT ARRAY WRAPPER OMIT QUOTES) as title,
    json_query(data, 'strict $.title_ascii' WITHOUT ARRAY WRAPPER OMIT QUOTES) as title_ascii,
    json_query(data, 'strict $.ticket_type_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as ticket_type_id,
    json_query(data, 'strict $.case_note' WITHOUT ARRAY WRAPPER OMIT QUOTES) as case_note,
    json_query(data, 'strict $.follow_up_date' WITHOUT ARRAY WRAPPER OMIT QUOTES) as follow_up_date,
    json_query(data, 'strict $.escalate_room_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as escalate_room_id,
    json_query(data, 'strict $.escalate_agent_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as escalate_agent_id,
    json_query(data, 'strict $.escalate_follow_up_date' WITHOUT ARRAY WRAPPER OMIT QUOTES) as escalate_follow_up_date,
    json_query(data, 'strict $.escalate_status' WITHOUT ARRAY WRAPPER OMIT QUOTES) as escalate_status,
    json_query(data, 'strict $.escalate_note' WITHOUT ARRAY WRAPPER OMIT QUOTES) as escalate_note,
    json_query(data, 'strict $.escalate_by' WITHOUT ARRAY WRAPPER OMIT QUOTES) as escalate_by,
    json_query(data, 'strict $.escalate_date' WITHOUT ARRAY WRAPPER OMIT QUOTES) as escalate_date,
    json_query(data, 'strict $.created_by' WITHOUT ARRAY WRAPPER OMIT QUOTES) as created_by,
    json_query(data, 'strict $.created_date' WITHOUT ARRAY WRAPPER OMIT QUOTES) as created_date,
    json_query(data, 'strict $.updated_by' WITHOUT ARRAY WRAPPER OMIT QUOTES) as updated_by,
    json_query(data, 'strict $.updated_date' WITHOUT ARRAY WRAPPER OMIT QUOTES) as updated_date,
    json_query(data, 'strict $.status' WITHOUT ARRAY WRAPPER OMIT QUOTES) as status,
    json_query(data, 'strict $.reason' WITHOUT ARRAY WRAPPER OMIT QUOTES) as reason,
    json_query(data, 'strict $.sms_scheduler_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as sms_scheduler_id,
    json_query(data, 'strict $.is_sms_sent' WITHOUT ARRAY WRAPPER OMIT QUOTES) as is_sms_sent,
    json_query(data, 'strict $.email_scheduler_id' WITHOUT ARRAY WRAPPER OMIT QUOTES) as email_scheduler_id,
    json_query(data, 'strict $.is_email_sent' WITHOUT ARRAY WRAPPER OMIT QUOTES) as is_email_sent,
    json_query(data, 'strict $.ticket_category' WITHOUT ARRAY WRAPPER OMIT QUOTES) as ticket_category,
    json_query(data, 'strict $.last_call_datetime' WITHOUT ARRAY WRAPPER OMIT QUOTES) as last_call_datetime,
    json_query(data, 'strict $.close_ticket' WITHOUT ARRAY WRAPPER OMIT QUOTES) as close_ticket,
    json_query(data, 'strict $.installment' WITHOUT ARRAY WRAPPER OMIT QUOTES) as installment,
    json_query(data, 'strict $.total_payment' WITHOUT ARRAY WRAPPER OMIT QUOTES) as total_payment,
    json_query(data, 'strict $.previous_payment' WITHOUT ARRAY WRAPPER OMIT QUOTES) as previous_payment,
    json_query(data, 'strict $.previous_payment_date' WITHOUT ARRAY WRAPPER OMIT QUOTES) as previous_payment_date,
    json_query(data, 'strict $.remaining_dept' WITHOUT ARRAY WRAPPER OMIT QUOTES) as remaining_dept,
    json_query(data, 'strict $.promise_date' WITHOUT ARRAY WRAPPER OMIT QUOTES) as promise_date,
    json_query(data, 'strict $.promise_target' WITHOUT ARRAY WRAPPER OMIT QUOTES) as promise_target
from parsed